version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - /var/lib/postgresql/data/
    restart: always

  backend:
    image: deonisg/food_backend
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/recipes/
    depends_on:
      - db
    env_file: .env
    restart: always

  frontend:
    image: deonisg/food_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/recipes/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always
