# Generated by Django 3.2.13 on 2023-08-21 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления должно бытьне менее 1 минут(ы)!')], verbose_name='Время приготовления'),
        ),
    ]
